// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbyTMm-fg5w0OWwoLIpQhdSdcb3UbXPjE',
    appId: '1:396474982350:web:65ba1e1b24398a642e159f',
    messagingSenderId: '396474982350',
    projectId: 'chat-8500b',
    authDomain: 'chat-8500b.firebaseapp.com',
    storageBucket: 'chat-8500b.firebasestorage.app',
    measurementId: 'G-ZQY4WR99YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ9_sjJxnNoz2axIVnUVLXl8iHk1D2VYs',
    appId: '1:396474982350:android:da78a50fdd44db672e159f',
    messagingSenderId: '396474982350',
    projectId: 'chat-8500b',
    storageBucket: 'chat-8500b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5aqYWhiMqnNo8u5r_x7_8uYiLFnqAAiM',
    appId: '1:396474982350:ios:c4c680f53f07bf762e159f',
    messagingSenderId: '396474982350',
    projectId: 'chat-8500b',
    storageBucket: 'chat-8500b.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5aqYWhiMqnNo8u5r_x7_8uYiLFnqAAiM',
    appId: '1:396474982350:ios:c4c680f53f07bf762e159f',
    messagingSenderId: '396474982350',
    projectId: 'chat-8500b',
    storageBucket: 'chat-8500b.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbyTMm-fg5w0OWwoLIpQhdSdcb3UbXPjE',
    appId: '1:396474982350:web:cd53f349e969560e2e159f',
    messagingSenderId: '396474982350',
    projectId: 'chat-8500b',
    authDomain: 'chat-8500b.firebaseapp.com',
    storageBucket: 'chat-8500b.firebasestorage.app',
    measurementId: 'G-TX4NSHE9ZN',
  );
}
